### ISSUE TITLE
[question]: gaussian process in replicated pattern

### ISSUE THREAD

**Issue by slwu89** [spatstat/spatstat#101]
hello spatstat team,

I'm trying to fit a Gaussian process model to replicate data, using `mppm`; I'm curious if there has been any update in the reccomended manner in which to do this since this post: https://stat.ethz.ch/pipermail/r-sig-geo/2013-December/020053.html Also the syntax of some of the commands seems to have changed sufficiently since 2013 that the code presented here no longer functions properly.

I was unable to find a way to do it via the documentation or the book "Spatial Point Patterns".

Thank you for any information!

**Comment by baddstats** [comment]
Please do not use the Issues page to ask questions. It is too clunky for correspondence. You can use stackoverflow, or write directly to the package authors, to ask questions.

Use `pool` to combine K-functions. 

The code you cited will still work if the line `Data$Lambda <- Lam` is replaced by `Data$Lambda <- Lam$trend`. That change is needed because the default result of `predict.mppm` has changed. 

Otherwise everything in the cited code still works. Instead of pooling by hand, you just type `pool(K)`

**Comment by slwu89** [comment]
Understood, will use those other forums for further questions. Thank you for the quick response!
