### ISSUE TITLE
sf - spatstat interface?

### ISSUE THREAD

**Issue by ratnanil** [spatstat/spatstat#104]
Since `sf` is proving to become a defacto standard for spatial vector  data in `R`, are there any plans to build a simple `spatstat`-`R` interface somewhere in the future? This question has been addressed before in https://github.com/spatstat/spatstat/issues/69#issuecomment-363713991, but I'm not sure how the final verdict on the question is. 

@rubak wrote:
> This is part of a much larger issue of how to interface with sf which seems to quickly become the standard tool for spatial data manipulation in R (for good reasons -- I enjoy the package too). [...] I would rather think an interface package would be a nice solution. This could make it possible to both input and output sf objects and use the pipe operator naturally etc.

to which @edzer replied: 
> sf currently imports some spatstat objects: see https://github.com/r-spatial/sf/blob/master/R/spatstat.R . Happy to move that to an interface package, we could also extend here since there is already a soft dependency (spatstat in Suggests:).

It would be great if the two packages worked in a more integrative manner..

**Comment by baddstats** [comment]
The answer is the same - there are no plans to write an interface package to convert between `sf` and `spatstat` classes. Feel free to write one.

For a long time, `maptools` was the recommended interface package, which allowed users to read in data from various file formats into `sp` classes, and convert from `sp` data types to other data types used in different packages including `spatstat`. 

With the rising popularity of `sf` it would make sense to write an interface package for conversion of other data types to and from `sf` classes. However this is not a priority for the authors of `spatstat` (basically because statisticians do not get professional recognition for writing software unless it includes new statistical techniques).

**Comment by ratnanil** [comment]
ok, thanks for this clarification. @edzer, any plans on your side? I _could_ look into writing something myself, although I'm not sure if I have the required skills for such a task.

**Comment by edzer** [comment]
Help is always welcome! A bit of what you're looking for is already here: https://github.com/r-spatial/sf/blob/master/R/spatstat.R - this ia only spatstat -> sf. It would also be good to have conversion methods from spatstat's `im` to and from `stars` objects.

**Comment by ratnanil** [comment]
I'll see what I can do.. but it might take a while.
