### ISSUE TITLE
With r 3.6, "Registered S3 method overwritten by 'spatstat'

### ISSUE THREAD

**Issue by michdn** [spatstat/spatstat#107]
Just after I updated to R 3.6.1, I started getting warning messages about S3 methods being overwritten (which I understand to now be verbose with R version 3.6.0, https://cran.r-project.org/doc/manuals/r-devel/NEWS.html).

Registered S3 method overwritten by 'spatstat':
  method     from
  print.boxx cli 

(I know the following is from a different package, but it was the best discussion about this type of issue that I could find: https://github.com/r-lib/rlang/issues/669 )

Thanks!

**Comment by baddstats** [comment]
The packages `spatstat` and `cli` both contain a class `boxx` with a print method. The messages from R 3.6.x are correct, and warn users about this conflict. 

You can use `suppressMessages` to hide the message. 

It would be possible to remove the conflict by renaming one of the functions. Unfortunately we can’t do that in `spatstat` because the function is documented in our 2015 book and we are committed to preserving accuracy of the book as long as possible.

**Comment by michdn** [comment]
Thank you for the info!
