### ISSUE TITLE
xlab/ylab options for plot.im/image method

### ISSUE THREAD

**Issue by TWilliamBell** [spatstat/spatstat#127]
I was trying to use spatstat to do some basic density plots, and when I did them, x- and y-labels wouldn't plot.  I ended up having to use ```mtext``` from base R, which seems like over kill for what is supposed to be a rather generic operation.  Is this a known issue or an issue that there are plans to deal with?

I can provide a minimal example if necessary.

**Comment by rubak** [comment]
Yes, it would be convenient if you could provide a minimal example. This is supposed to work.

**Comment by TWilliamBell** [comment]
Here is an example that doesn't work for me.

```
ex <- matrix(data = runif(2000), ncol = 2)

window <- spatstat::owin(c(-100, 100), c(-100, 100))

pppo <- spatstat::ppp(x = ex[ , 1],
                      y = ex[ , 2], window)

den <- density(pppo, kernel = "gaussian", 
               edge = T, diggle = F, adjust = 1)

par(mar = c(5, 2, 2, 0.5)+0.1)

spatstat::plot.im(den, main = "", col = viridisLite::viridis(15),
      xlab = "Real Part", ylab = "Imaginary Part")
```

**Comment by rubak** [comment]
OK. I didn't read your first post properly since I was on the phone and missed the fact that you were talking about `plot.im` (as your title clearly states). I thought it was a statement about `spatstat` objects in general such as plots of Ripley's K-function etc. where `xlab` and `ylab` work out of the box.

It is true that objects with spatial axes (`im` or `ppp`) don't support `xlab` and `ylab` since they are rarely used. Spatial objects typically represent things on a geographical map where it is just implicitly assumed that North is up without putting axis labels saying "Easting" and "Northing"  or they represent e.g. things in a microscopy image where the coordinate system is arbitrary and there wouldn't be much information is labels saying "x coordinate" and "y coordinate". I think there are some technical difficulties is getting this to work in easily in the default code, which may not be worth the effort due to the rare use case, and with the relatively simple workaround of using `mtext`.

I will think about maybe leaving this open as a feature request and see if it gets a lot of attention.

**Comment by baddstats** [comment]
As @rubak says, there is no general reason why a particular `plot` method should be expected to behave the same as the default `plot` method. (That's why there are different plot methods adapted to different types of data,) So there's no reason why `plot.im` should *have* to accept `xlab, ylab`.

However, the feature you're requesting is actually supposed to work, in the sense that `plot.im` and `plot.ppp` pass the arguments `xlab` and `ylab` down to `plot.owin`, but .. sometime in the last 25 years, `plot.owin` has changed so that it now effectively ignores these arguments (`plot.owin` calls `plot.default` with `type="n", ann=FALSE, axes=FALSE` so the labels are not plotted). 

I will insert a line in `plot.owin` that detects `xlab,ylab` and adds the labels using `mtext`.

**Comment by baddstats** [comment]
On further investigation, I've decided that this does not require a change to the code.
I will add some information in the help files for the plot methods.

Short answer: to get what you want, specify `ann=TRUE` as well as `xlab` and `ylab`.

Long answer:  the `plot` methods for `spatstat` spatial objects (such as images, windows and point patterns) call `plot.default`, with the arguments `axes=FALSE, ann=FALSE`(by default) so that axes are not plotted or labelled. However these default arguments can be overridden by adding them in the call to the plot method.  Example:

     plot(letterR, axes=TRUE, ann=TRUE, xlab="Easting", ylab="Northing")
     plot(letterR,            ann=TRUE, xlab="Easting", ylab="Northing")

**Comment by baddstats** [comment]
Uh, sorry, that is for `owin` objects. I will have to tweak `plot.im`

**Comment by baddstats** [comment]
This now works for `plot.im` in `spatstat 1.63-0.019`
Example:
      
    Z <- density(cells)
    plot(Z, axes=TRUE, ann=TRUE, xlab="Easting", ylab="Northing")
    plot(Z,                      ann=TRUE, xlab="Easting", ylab="Northing")

**Comment by baddstats** [comment]
For `plot.im` and `plot.owin` this now works in the public release `spatstat 1.63-2` available from CRAN.

**Comment by baddstats** [comment]
This also works for `plot.ppp` in the development version `spatstat `1.63-2.001`

**Comment by baddstats** [comment]
Example

     plot(humberside, axes=TRUE, ann=TRUE, xlab="Easting", ylab="Northing")
     plot(humberside,            ann=TRUE, xlab="Easting", ylab="Northing")
     plot(humberside, axes=TRUE)
