### ISSUE TITLE
Scaling of linim objects

### ISSUE THREAD

**Issue by MarcSchneble** [spatstat/spatstat#153]
Hello,
I just ran code with the latest version of spatstat on CRAN which gave me different results than with the version 1.64-1. When I consider the following example
```
library(spatstat)
set.seed(1)
X <- runiflpp(100, simplenet)
sigma <- bw.lppl(X, distance = "path")
fit <- density.lpp(X, sigma = as.numeric(sigma))
fit_scaled <- fit/integral(fit)
integral(fit_scaled)
```
spatstat version 1.64-1 returns a value of 1 for `integral(fit_scaled)` (what could be expected) and with the latest spatstat version 2.2-0 I get a value of 0.009987743 which does not make sense here. I think there is an issue with the scaling of the linim objects or the method`integral.linim` in the new version. Could you please check?

Thanks,
Marc

**Comment by rubak** [comment]
Hi Marc,

It is the line `fit_scaled <- fit/integral(fit)` that doesn't work as expected. It ends up converting the result to an `im` rather than a `linim` object. Then the integral is in the Euclidean plane rather than on the network. A simple workaround for now is:

```r
library(spatstat)
set.seed(1)
X <- runiflpp(100, simplenet)
sigma <- bw.lppl(X, distance = "path")
fit <- density.lpp(X, sigma = as.numeric(sigma))
int <- integral(fit)
fit_scaled <- eval.linim(fit/int)
integral(fit_scaled)
```

@baddstats since the second argument isn't a `linim` the code gets caught here:
https://github.com/spatstat/spatstat.linnet/blob/6d3ce7f6a80c31d5623156841542a6100f914127/R/Math.linim.R#L66

**Comment by MarcSchneble** [comment]
Hi Ege,
thanks for the prompt reply and the workaround!
Best,
Marc

**Comment by baddstats** [comment]
Thank you for spotting this. 
The bug has been fixed in development version `spatstat.linnet 2.2-0.002` available on GitHub.
