### ISSUE TITLE
Pool rhohat estimates

### ISSUE THREAD

**Issue by danielmanriquecastano** [spatstat/spatstat#157]
Dear team,

I appreciate very much the effort you have put into the development of this package. I'm working with a hyperframe of replicated point patterns. Following the guidance in the book, I have no problem in pooling G or K-functions to represent groups. However, a problem arises when I try to pool rhohat and other estimates. The following error is displayed:

Error in attributes(sumY) <- attributes(template) : 
  'names' attribute [6] must be the same length as the vector [5]

Unlike the K function (5 columns), the results of this rhohat (with a covariate) has 6 columns and for some reason the function does not work. I did not find additional alternatives to pool Rhohat-generated .Fvs. 

This is the code I am implementing:

I generate a column with the rhohat estimates for each point pattern`

`  Point_Patterns$Astrocytes_Rho = with(Point_Patterns, rhohat(Astrocytes, Neurons_Dens, method="tr", horvitz=TRUE)) ` 

And I try to generate a new object by separating the created column by 1 factor (DPI) and pooling the point patterns. It works well for k functions but not for Rhohat, for instance.

` New_Frame <- anylapply(split(Point_Patterns$Astrocytes_Rho, Point_Patterns$DPI), pool) ` 

I would appreciate your support on this issue.

Edit: I was trying to make some debugging (image attached) and the problem is in the presented line. For some reason, it is eliminating the "var" variable from the table in the line "  sumY <- Reduce(Add, Y)" of the pool.fv core code.

![Screenshot 2022-08-17 182641](https://user-images.githubusercontent.com/20017235/185254796-d8b10a1c-598a-4d53-81bc-f961ade79fba.png)

**Comment by baddstats** [comment]
Thank you for drawing attention to this error message.

First I should warn you that the `pool` operation may not be equally valid for different kinds of summary functions. It depends on details of the estimation procedure which computed the functions. You can generally assume that, if the original command has an argument `ratio` (as for example `Kest` does) then pooling is valid and the calculations are the optimal ones, but if there is no `ratio` argument (as for example `rhohat` does not) then pooling is performed using a simpler, less theoretically justified technique. It generally still works but is not optimal. 

Anyway, I have fixed this bug in `pool.fv` in the current development version of `spatstat.explore` (2.999-999.029). So it should now work for you.

To make life a bit simpler, I have also given `rhohat` a new argument `do.CI=TRUE`. I suggest that you calculate the individual `rhohat` functions with `do.CI=FALSE`. Then the individual functions will not contain the individual estimates of variance, standard error, upper and lower limits of confidence bands. We don't need these individual estimates because we will be using the pooled variance. This will reduce the amount of clutter and make it easier to do the analysis.
