### ISSUE TITLE
is.subset.owin does not recognise real subset

### ISSUE THREAD

**Issue by ouroukhai** [spatstat/spatstat#166]
Hello spatstat team,
I recently noticed the following behavior:

```r
# seed for replication
set.seed(123)

# indexes to split the point process
index <- sample(1:npoints(lansing), 0.6 * npoints(landing))

# random points
lansing_1 <- lansing[index]
# the rest
lansing_2 <- lansing[-index]

# some number to move some points
plus <- 10

# move second pattern diagonal
lansing_2$x <- lansing_2$x + plus
lansing_2$y <- lansing_2$y + plus
lansing_2$window$xrange <- lansing_2$window$xrange + plus
lansing_2$window$yrange <- lansing_2$window$yrange + plus

# Keep as A the first subset
A <- Window(lansing_1)
# Keep as B the union
B <- union.owin(Window(lansing_1), Window(lansing_2))
is.subset.owin(A, B) # FALSE!
``` 
Even though A is a subset of B, it is not recognized as one. 
Thank you very much for your time!
Sincerely,

**Comment by ouroukhai** [comment]
Thank you for the answer. I also run the function is.subset.owin and it seems to return FALSE because of this line: 
```r
bx <- crossing.psp(edges(A), edges(B))
  if (npoints(bx) > 0) 
    return(FALSE)
``` 
before the as.mask() procedures. Is this the intended behavior?

**Comment by ouroukhai** [comment]
The function's inability to identify one of two rectangles that form a union as a subset appears unusual.

**Comment by rubak** [comment]
Of course this can be improved, and you are welcome to try to device a pull request that makes the algorithm better. In general computational geometry is challenging due to numerical precision of computers, so it may be difficult to make a really good algorithm that works in general. I agree that it may seem surprising that this example fails, but if you trim a tiny sliver of A away (one millionth of a unit) the algorithm is able to correctly determine that A (trimmed) is a subset of B. Here is your example with two extra lines of code to show this:

```r
# seed for replication
set.seed(123)

# indexes to split the point process
index <- sample(1:npoints(lansing), 0.6 * npoints(lansing))

# random points
lansing_1 <- lansing[index]
# the rest
lansing_2 <- lansing[-index]

# some number to move some points
plus <- 10

# move second pattern diagonal
lansing_2$x <- lansing_2$x + plus
lansing_2$y <- lansing_2$y + plus
lansing_2$window$xrange <- lansing_2$window$xrange + plus
lansing_2$window$yrange <- lansing_2$window$yrange + plus

# Keep as A the first subset
A <- Window(lansing_1)
# Keep as B the union
B <- union.owin(Window(lansing_1), Window(lansing_2))
is.subset.owin(A, B) # FALSE!

Atrim <- erosion(A, 1e-6)
is.subset.owin(Atrim, B) # TRUE
```

**Comment by ouroukhai** [comment]
Thank you very much for taking the time to answer. I am still learning how to handle the package, so I cannot suggest an algorithm change. I enjoy the ways it helps me with my analyses. I have struggled with seemingly simple handles like the one you suggested. Most of my problems came from handling unions of rectangles, and it was very frustrating (i.e. could not use an envelope on Fest because the envelope() function returned FALSE on is.subset.owin()), and not something I found in your book (I have not read the whole thing yet). Is this the proper (suggested) way to handle similar situations? I had trouble with simulations on small rectangles (windows) in vast areas (a few points were accepted), and maybe I should ask this in your forum and not in an issue thread. Anyway, thank you for the time. I will leave the thread open in case you could reply to my questions, but my initial question is answered.
Sincerely,

**Comment by baddstats** [comment]
I have modified `is.subset.owin` in the case where the two polygons share some common boundary segments.
It now gives the result as `TRUE` in your example.

The updated code is available from [the GitHub repository](https://github.com/spatstat/spatstat.geom) as `spatstat.geom 3.2-7.002` 

Notes: 

1. `union.owin` sometimes changes the coordinates of the polygon vertices (because the computation is performed by the `polyclip` package which discretises the coordinates). Accordingly you may still get unexpected results. Use `vertices(B)` to examine the coordinates of the vertices of the union of the windows.
2. To shift a spatial object in `spatstat`, use the function `shift` rather than changing the internal data of the object.

**Comment by ouroukhai** [comment]
Thank you, @baddstats, this was very helpful!
