### ISSUE TITLE
Summary function fails on fitted object when using method="logi"

### ISSUE THREAD

**Issue by kcolyvas** [spatstat/spatstat#30]
Following on from the recent issue that was fixed in spatstat 1.47-0.034
where method="logi" did not support a data frame of covariates.
The function summary fails on the fitted model object, however printing the object by typing its name works. 

Sorry I can't provide details of the error message as I am not a work, but he previous issue submission has a data set and code that could be used to test this.

Regards,
Kim Colyvas

**Comment by baddstats** [comment]
This occurs when the data frame contains NA values. (The NA's are dropped in some circumstances and retained in others, leading to a mismatch in the dimensions of data frames.)

An immediate workaround is to remove data that contains NA's. Either remove columns of the data frame that contain NA values (and of course remove these variables from the model formula), or remove rows of the data frame that contain NA's and remove the corresponding data points from the quadrature scheme.

This bug has been fixed in `spatstat 1.47-0.050`.
