### ISSUE TITLE
Question: why depend on >= 3.3.0?

### ISSUE THREAD

**Issue by MichaelChirico** [spatstat/spatstat#35]
I tried searching the news for why `spatstat` now depends on 3.3.0 or higher, but came up short.

I am trying to use it on a server where I don't have root privileges to upgrade R that runs 3.2.3... I lied and edited the DESCRIPTION so that it would install. Now I'm wondering what problems this might cause exactly -- if it's limited to a few functionalities, it probably won't cause any issues.

Thanks!

**Comment by baddstats** [comment]
**We never upgrade the version requirements unless we really have to**.  
This is because we know that some people only have access to older versions of R.

However, in the case you describe (*only* for `spatstat 1.48-0` and `R 3.2.3`, and recompiling from sources) you should be able to get away with it. After tweaking the 'Depends' rule, make sure that you re-build `spatstat` using `R 3.2.3`. You will get a package tarball that **only** works under `R 3.2.3`.

 If  you encounter problems with this, try also setting `ByteCompile: false` in the `DESCRIPTION` file (this will slow down the package by 30% but will make it less fragile.)

Without going into too many details, byte-compiled code has rigid expectations about the number of arguments each function has. When `R 3.2.3` upgraded to `R 3.3.0`, some of the base functions had changes to their argument lists, so it is not possible to have a byte-compiled package that works simultaneously with `R 3.2.3` and `R 3.3.0`.

I stress that this is an exception because of the particular circumstances. Our policy is that the `Depends` rule specifies the oldest version of `R` with which `spatstat` will work.
