### ISSUE TITLE
ppp lose attributes when manipulated

### ISSUE THREAD

**Issue by ute** [spatstat/spatstat#52]
Subsetting and other manipulations make point patterns lose some of their attributes. For cluster point processes, it means they lose their parents and become orphans. Is this behaviour intended?
```
X <- rMatClust(10, 0.05, 4)
attributes(X)
attributes(X[square(1)])
attributes(shift(X, c(0,0)))
```
If necessary, backwards compatibility could e.g. be ensured by a spatstat option `keep.ppp.attributes` that defaults to `FALSE`.

**Comment by baddstats** [comment]
This behaviour is intended. These attributes are not part of the definition of the `ppp` class. 

It is commonplace in `R` that a function's return value has attributes which are used to convey additional information. This information has to be extracted immediately after the function call, in order to handle it. 

We don't plan to extend the `ppp` class to handle such attributes. That would be a lot of work and would result in slower code. Sorry for the inconvenience..

**Comment by ute** [comment]
Thanks! Was a stupid example anyway. Any plans future piggyback containers to spatstat objects that could transport extra information? I guess no...
