### ISSUE TITLE
dpp simulate: nsim > 1 impossible and W ignored?

### ISSUE THREAD

**Issue by AdriMaz** [spatstat/spatstat#68]
Hello all,

It is impossible to simulate more than one dpp with `simulate` function when the dimension is not 2. For example:

```
model <- dppGauss(lambda = 50, alpha = 0.03, d = 3)
simulate(model, nsim = 2)
```
returns
```
Error in (function (..., check = TRUE, promote = TRUE, demote = FALSE)  :
  Some arguments of solist() are not 2D spatial objects
```

I can compute myself the Fourier eigenvalues and use `rdpp` function to avoid to repeat these operations, but it will be appreciable to fix it...

Moreover, always when the dimension is not 2, the parameter `W` is ignored:
```
model <- dppGauss(lambda = 50, alpha = 0.03, d = 3)
W <- boxx(rep(list(0:1), 3))
simulate(model, nsim = 1, W = W)
```
returns 
```
Three-dimensional point pattern
40 points
Box: [-0.5, 0.5] x [-0.5, 0.5] x [-0.5, 0.5] units
```
It seems that the parameter `Wowin` remains `NULL` since a `boxx` object is not a `owin` object
([line 273](https://github.com/spatstat/spatstat/blob/master/R/simulate.detPPF.R#L273)), but I do not understand why it is taken into accout when `d = 2`...

(I am using spatstat_1.54-0 with R 3.4.2).

Thanks!

Adrien

**Comment by baddstats** [comment]
Thank you for alerting us.

The first problem, that the code failed when `nsim > 1`, is now fixed in the development version `spatstat 1.54-0.014`.

The second problem, concerning the argument `W`, needs more work. The code does not ignore `W`, and it correctly handles the *size* of the box, but assumes that the box will be centred about the origin. I could fix this but we need to check whether symmetry is a mathematical requirement - over to you, Ege @rubak

**Comment by rubak** [comment]
No, it is not a mathematical requirement. It is just poor coding on my end. I will fix it now.

**Comment by AdriMaz** [comment]
Thanks to both of you for the quick reply!
