### ISSUE TITLE
Add support for "bbox" classes from sf objects

### ISSUE THREAD

**Issue by angela-li** [spatstat/spatstat#69]
It would be great if the function as.owin( ) could take objects of class "bbox" as an argument for W. bbox objects are produced by the ["st_bbox" function](https://github.com/r-spatial/sf/blob/b0e68cd1305f485967f4e22b286076f71b5d48c9/R/bbox.R) in Edzer Pebesma's sf package.

For reference, objects of class bbox look as follows, and it isn't much work to change them into 4-element vectors to use in as.owin( ). But, it would be nice to explicitly support objects of class "bbox".

\> bbox_obj
    xmin     ymin     xmax     ymax 
722912.5 193399.7 754030.8 215725.3 
\> class(bbox_obj)
[1] "bbox"

**Comment by angela-li** [comment]
An interface package would be helpful! You're right that there's almost too much in the `spatstat` package. It would be a pain to go through and rewrite it to take `sf` objects.

I wonder if Edzer has anything under development with regards to this. I'm no `sf` expert, but it would be useful to build out the ecosystem of packages surrounding/supporting `sf`.

I'd be interested in helping out with this, but I don't know that much about `spatstat`. What ideas/suggestions do you have for an interface package? Would it just be for `sf`-`spatstat` connections?

**Comment by edzer** [comment]
sf currently imports some spatstat objects: see https://github.com/r-spatial/sf/blob/master/R/spatstat.R . Happy to move that to an interface package, we could also extend here since there is already a soft dependency (spatstat in Suggests:).

**Comment by rubak** [comment]
OK. I guess I will have to discuss with @baddstats what a good approach could be. I'm on my way off to two weeks vacation :-), so it will take some time before anything happens. We will leave the issue open for now and discuss from there.

**Comment by baddstats** [comment]
Enjoy your well-earned holiday, @rubak. 

Our policy in `spatstat` is not to support other classes/formats of data because it is more efficient and reliable to perform data format conversion in a single place, typically an interface package such as `maptools`.

However, the default method `as.owin.default` in `spatstat` already handles several formats similar to  `bbox`, such as the `xl, xu, yl, yu` format used in Brian Ripley's `spatial` package. These have been supported because they can be detected without referring to the class structure, so that we don't have to make `spatstat` depend on the originating package; and because there is low risk of misinterpreting the data format. 

So I will make an exception in this case and add the`bbox` (or rather: `xmin, xmax, ymin,ymax`) format to `as.owin.default`.

I also want to repeat the caution from @rubak that there is a methodological problem: methods developed for a flat plane do not necessarily work correctly for a curved surface, so one cannot unthinkingly ignore the CRS information.

**Comment by baddstats** [comment]
Implemented in development version `spatstat 1.55-0.010`
