### ISSUE TITLE
parres() function --- `Fitting algorithm for ‘glm’ did not converge` warning

### ISSUE THREAD

**Issue by elgabbas** [spatstat/spatstat#8]
Hello all,

I am having a problem with the `parres()` function, with a ppm model having interactions between covariates.

I am receiving an error like:
`	Error in parres(model = CurrPPM, covariate = "Var1")`
`	The covariate ‘Var1’ cannot be separated from the covariates ‘Var2’ and ‘Var3’ in the model terms ‘Var1:Var2’ and ‘Var1:Var3’`

While running the ppm model, I've used a formula like: ` as.formula(~(Var + Var2 + Var3)^2 + I(Var1^2) + I(Var2^2) + I(Var3^2))` to include all variables, their quadratic terms and all possible combinations. Then I've used the `MASS:::stepAIC()` function to select the best model out of the initial model. When I am trying to do some model diagnostics, it works fine except for the `parres()` function. The covariates were provided to the model as original variables, and I am using the formula mentioned above to include the interactions on the fly while running the model. i.e. I provided just a list of 3 real-valued pixel image (class: `im`) not the interactions or the quadratic terms and they were calculated properly while running the model. Is that the cause of the error message I am receiving? Should I prepare, as much as I need, real-valued pixel images (`im`) of the interactions and quadratic terms and provide them explicitly as covariates?

Another thing, I am always receiving a warning message of: ` *** Fitting algorithm for ‘glm’ did not converge ***` even if the model takes somehow much time to process. I've tried to use something like: `glm.control(maxit = 1000)` but it does not help much. Is it ok to ignore this warning message? or I should do some other steps to avoid such warnings? In one of my cases, there is `81` points and `590083` dummy points. Is the number of points not enough to run a reasonable ppm model compared to the used number of dummy points?

Thanks,
Ahmed

**Comment by elgabbas** [comment]
Hello Prof. @baddstats & @rubak,
Is there any reply concerning that issue?

Thanks in advance,
Ahmed

**Comment by baddstats** [comment]
Hi, sorry for the delay, we have been busy finishing our book on spatstat.
The partial residual for a covariate is only defined when the covariate has no interactions with other covariates. It would be possible to trick the software by first fitting the desired model, then using model.images to extract images of the canonical covariates, then renaming the entries, and fitting a fake model with these images as its covariates. However, I'm not sure what interpretation can be placed on the result. Even in linear regression, people only do partial residuals for additive models.

Regarding your other question, one common reason why the glm fitter would fail to converge is that the values of the canonical covariates in the model are very large. Your model formula involves the squares and cubes of original covariates, so this is likely to be the problem. You could try rescaling the original covariates so that their average value is closer to 1. 

If rescaling doesn't help, it's most likely that the model is almost confounded i.e. the design matrix is almost singular. This can happen when several terms are closely related. For example if Var1 is almost constant, then I(Var1^2) will be strongly correlated with Var1.

Adrian

**Comment by rubak** [comment]
Hi @elgabbas did Adrian's reply solve your problem? I that case I will go ahead and close this issue...

**Comment by elgabbas** [comment]
Yes, it was helpful..
Actually, I have to say earlier: thanks for the reply, but so far I've not applied that so I am not sure if I will face simillar issue again.
I will close this issue, and in the case of extra comment/s I will re-open it again.
Thanks, Ahmed
