### ISSUE TITLE
Bug in Finhom

### ISSUE THREAD

**Issue by rubak** [spatstat/spatstat#88]
Reported at StackOverflow: <https://stackoverflow.com/q/53428594/3341769>

When `Finhom` is called without argument `lambda` it behaves differently than if a vector of leave-one-out estimated intensities is provided as `lambda`.

When `lambda = NULL` it calculates the leave-one-out estimate in [line 199 here](https://github.com/spatstat/spatstat/blob/master/R/Jinhom.R#L199). Later in [line 249](https://github.com/spatstat/spatstat/blob/master/R/Jinhom.R#L249) the minimum `lmin` is evaluated over a grid, which can be an extremely small value causing numerical unstability. When a vector is provided for `lambda` the minimum `lmin` is set to `min(lambdaX)` [in line 266](https://github.com/spatstat/spatstat/blob/master/R/Jinhom.R#L266), where `lambdaX` is just the input vector `lambda`. This is completely different, but I haven't looked at what is correct yet. Hopefully the latter is correct since it gives much nicer results...

**Comment by baddstats** [comment]
I responded to the StackOverflow thread.

The different behaviour is a bit disconcerting, but this is the way it was designed by the original contributors. I will consult them for advice.

The theory requires that `lmin` should be a lower bound on the intensity at any location. So this would appear to dictate that the current behaviour should occur!

The original poster's example is not a good one, because the bandwidth is severely underestimated, so that the minimum over the grid is much smaller than the minimum at data points. I get much better (and more consistent) results by simply using another bandwidth selector.

**Comment by baddstats** [comment]
I have not found a solution which works well in all possible cases. 

The best solution may be simply to issue a warning when the value of `lmin` is much smaller than `min(lambdaX)` implying that the function estimate may be severely inflated. This can be done by examining `lratio` after
[line 274](https://github.com/spatstat/spatstat/blob/master/R/Jinhom.R#L274). 

I will do this in any case, and we can see if that is sufficient.

**Comment by rubak** [comment]
OK. Sounds like a good solution for now. I guess we should just close this issue and see what happens...

**Comment by baddstats** [comment]
The warning is now coded at [line 113-119](https://github.com/spatstat/spatstat/blob/master/R/Jinhom.R#L113-119) and
[line 288-294](https://github.com/spatstat/spatstat/blob/master/R/Jinhom.R#L288-294).
