### ISSUE TITLE
Fastest possible way to calculate pcf()

### ISSUE THREAD

**Issue by mhesselbarth** [spatstat/spatstat#95]
I need to calculate the pair correlation function multiple times as fast as possible. During the re-calculations, the window and the number of points stay identical, but only single points change their location. 

The fastest way I came up so far is: 
```
 k_fun <- spatstat::Kest(X = pattern, correction = "none")) # estimate K-fct
 spatstat::pcf.fv(X = k_fun) # estimate pcf from K-fct
```

I was just wondering if I'm missing something to speed up the calculation. 

Thanks a lot, 
Max

**Comment by rubak** [comment]
Sorry, but as the Readme says we only use GitHub issues to handle proper bugs etc. and not for specific questions and advice. Either post your question on a venue like StackOverflow under the `spatstat` tag or on an email list like R SIG GEO or email us directly. Once you post/email your question please provide more details about the size of the pattern and be more specific about your setup. What does "the number of points stay identical, but only single points change their location" mean? Are there 1000 points and only a few of them change location? Btw: It is more common to estimate the pcf directly from the point pattern rather than via the K function. You can have a look at specifying a (shorter than default) vector of r-values for pcf and maybe `localpcf()` can be useful..
