### ISSUE TITLE
Labels in rhohat and roc missing

### ISSUE THREAD

**Issue by carbonmetrics** [spatstat/spatstat#96]
plots for neither `roc` nor `rhohat`  have x or y axis labels. 

```
X <-  rpoispp(function(x,y){exp(3+3*x)})
rho <- rhohat(X, "x")
plot(rho)
```

![Rplot](https://user-images.githubusercontent.com/40055991/55717929-22fe3e80-5a03-11e9-81a3-cd9ca6427e55.png)

```
R version 3.5.3 (2019-03-11)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.2 LTS
spatstat_1.59-0

```
What is the best way to add these labels?

**Comment by baddstats** [comment]
The tick marks and labels are missing because the plot margin has been reduced.
Increase the plot margin using `par(mar=c(5,4,2,2))` for example, and then re-run your plot command. 
See `help(par)` for details. 

(Tip: if you are switching between different types of plots which require different margin settings, do something like `oldpar <- par(mar=c(5,4,2,2)); plot(rho); par(oldpar)` to revert to the previous margin settings.)
